test for sprint4
itsmealbina/Sprint_4 pull request #1
Opened 2023-08-20 20:54 UTC by itsmealbina

2023-08-21 21:56 UTC, kadirovgm requested changes

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +
нужно исправить: не нужно для каждого вопроса писать отдельный метод, ведь они по сути одинаковые, меняется только входной параметр - номер вопроса

Мы должны избегать всякого повторения в коде, например, по паттерну программирования DRY 

Поэтому, пожалуйста, сделай один метод, который будет принимать в аргументы один параметр - номер вопроса или локатор этого вопроса, и будет по нему кликать

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +
нужно исправить: то же самое для get_answer 

Сделай один метод, который будет на вход принимать локатор вопроса, и будет возвращать ее значение

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +
нужно исправить: не нужно для каждого вопроса писать отдельный подскролл, для этого можно написать базовый метод скролла к определенному элементу, тогда этот базовый метод можно вызывать внутри метода клика по вопросу (у тебя они ниже)

метод скролла к определенному элементу (в аргументы получает локатор элементу) стоит сделать базовым и поместить в BasePage, так как такое может пригодится в разных сценариях нашего проекта, ведь мы всегда должны закладываться на масштабирование

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +    def scroll_to_button_bottom(self):
нужно исправить: стоит создать базовый метод скролла к определенному элементу и здесь ее переиспользовать

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +    def opens_new_window_by_click_yandex_logo(self, pattern_url):
нужно исправить: этот метод похож на тест, не стоит в методах уже прописывать ассерт проверки

мы подразумеваем, что методы POM страницы должны возвращать какой то результат, который уже в тестах может быть проверен

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +        assert new_tab in all_tabs, "Новая вкладка не открылась"
нужно исправить: открытие нового таба не гарантирует, что загрузилась нужная нам страница

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +    def open(self, url):
нужно исправить: это скорее базовый метод класса BasePage

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +    def __init__(self, browser, timeout=5):
нужно исправить: init лучше держать в базовом классе BasePage, при наследовании все init родительского класса наследуются для дочернего

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +class Main():
нужно исправить: Если придерживаться классических рекомендации POM, то тебе нужно наследоваться в этом классе от BasePage - как раз таки для того, чтобы наследовать его общие методы.

а в методах POM страницы Main вызывать базовые методы

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +
Нужно исправить: стоит добавить базовый класс - Base Page

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

Именно поэтому у BasePage не могут быть свои локаторы, ведь предполагается, что для методов BasePage подходят локаторы POM-страницы

2023-08-21 21:56 UTC, kadirovgm commented on pages/main_page.py
> +
Нужно исправить: стоит добавить базовый класс - Base Page

класс BasePage - это такой родительский класс, в котором содержатся общие методы, такие как: клик по определенному элементу, скролл к определенному элементу, ожидание определенного элемента, изменение табов итд.

То есть эти методы не привязаны к определенной странице, и могут быть переиспользованы в любой POM-странице, стоит сюда добавить именно такие методы.

Именно поэтому у BasePage не могут быть свои локаторы, ведь предполагается, что для методов BasePage подходят локаторы POM-страницы

2023-08-21 21:56 UTC, kadirovgm commented on pages/order_page.py
> +class Order(Main):
нужно исправить: стоит наследоваться от BasePage

2023-08-21 21:56 UTC, kadirovgm commented on pages/order_page.py
> +    def __init__(self, browser):
нужно исправить: все init в BasePage

2023-08-21 21:56 UTC, kadirovgm commented on tests/test_order_scooter.py
> +    main_page.opens_new_window_by_click_yandex_logo(urls.yandex_url)
нужно испоавить: один тест=одна проверка - принцип атомарности

это скорее новый тест-кейс

2023-08-22 06:39 UTC, itsmealbina commented on pages/dzen_page.py
забыла добавить в него класс, исправлю

2023-08-22 06:41 UTC, itsmealbina commented on pages/main_page.py
> +        assert new_tab in all_tabs, "Новая вкладка не открылась"
по остальным замечаниям понятно, спасибо
а тут не очень - эта проверка что открылся именно новый таб, а не в том же окне. Разбить на разные методы? открытие таба, потом проверка урла, и проверка видимости какого-нибудь элемента на странице
или просто убрать assert в этом методе, остальное оставить как есть?

2023-08-26 04:46 UTC, kadirovgm requested changes

2023-08-26 04:46 UTC, kadirovgm commented on pages/main_page.py
> +        assert new_tab in all_tabs, "Новая вкладка не открылась"
да, я не заметил, что ты ниже проверяешь еще и URL и элемент страницы, тогда все верно, и да, лучше здесь assert убрать и оставить только нижний

2023-08-26 08:24 UTC, itsmealbina commented on pages/main_page.py
> +
добавлен

2023-08-26 08:24 UTC, itsmealbina commented on pages/main_page.py
> +
добавлен

2023-08-26 08:28 UTC, itsmealbina commented on conftest.py
> +@pytest.fixture(scope = "function")
исправлено

2023-08-26 08:29 UTC, itsmealbina commented on pages/data.py
> +class user_with_2_metro_stations():
исправлено, ответы будут в answers.py

2023-08-26 08:30 UTC, itsmealbina commented on pages/main_page.py
> +
исправлено

2023-08-26 08:30 UTC, itsmealbina commented on pages/main_page.py
> +
исправлено

2023-08-26 08:32 UTC, itsmealbina commented on pages/main_page.py
> +
исправлено, в классе Base() теперь будут общие методы 
* scroll_to_element(locator)
* для клика на элемент
* открытия урла
* проверки на совпадение с ожидаемым значением урла

2023-08-26 08:33 UTC, itsmealbina commented on pages/main_page.py
> +    def scroll_to_button_bottom(self):
исправлено

2023-08-26 08:35 UTC, itsmealbina commented on pages/main_page.py
> +        assert new_tab in all_tabs, "Новая вкладка не открылась"
уже разбила)) вынесла проверку отображения элемента на странице и проверку урла в методы страницы dzen_page.py, куда забыла добавить классы при отправке задания

2023-08-26 08:36 UTC, itsmealbina commented on pages/main_page.py
> +    def open(self, url):
исправлено

2023-08-26 08:37 UTC, itsmealbina commented on pages/main_page.py
> +    def __init__(self, browser, timeout=5):
__init__ оставила и в дочерних классах, только у них еще добавила super().__init__(browser)

2023-08-26 08:37 UTC, itsmealbina commented on pages/main_page.py
> +class Main():
исправлено

2023-08-26 08:37 UTC, itsmealbina commented on pages/order_page.py
> +class Order(Main):
исправлено

2023-08-26 08:38 UTC, itsmealbina commented on pages/order_page.py
> +    def __init__(self, browser):
оставила __init__, только внутрь еще добавила super().__init__(browser)

2023-08-26 08:51 UTC, itsmealbina commented on tests/test_order_scooter.py
> +    main_page.opens_new_window_by_click_yandex_logo(urls.yandex_url)
в таком порядке был описан позитивный сценарий в самом задании. Вынесу проверки на редирект в отдельный файл тестов, чтобы тут не смешивать проверку оформления заказа и редирект на страницы

2023-08-27 09:22 UTC, itsmealbina commented on .gitignore
> +allure_results
добавлен

2023-08-28 20:21 UTC, kadirovgm approved these changes

2023-08-28 20:21 UTC, kadirovgm commented on conftest.py
> +    driver = webdriver.Firefox(executable_path=geckodriver_path, options=op)
нужно исправить: не получится ли обойтись без использования executable path? так как в таком случае будет сложно поддерживать проект в команде, когда несколько разработчиков

вот простой пример:
```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()

```

2023-08-28 20:21 UTC, kadirovgm commented on pages/answers.py
> +class answers():
отлично!

2023-08-28 20:21 UTC, kadirovgm commented on pages/base_page.py
> +class Base():
супер!

2023-08-28 20:21 UTC, kadirovgm commented on pages/dzen_page.py
> +        self.wait_for_element_visibility(dzen_page_locators.main_tab)
отлично, нужно именно так пользоваться базовыми методами

2023-08-28 20:21 UTC, kadirovgm commented on pages/main_page.py
> +    def scroll_to_question(self, number):
правильно!

2023-08-28 20:21 UTC, kadirovgm commented on pages/main_page.py
> +    def open_answer_for_question(self, number):
намного лучше и красивее

2023-08-29 06:54 UTC, itsmealbina commented on conftest.py
> +    driver = webdriver.Firefox(executable_path=geckodriver_path, options=op)
когда пробовала через Service, то при попытке запуска тестов появлялась ошибка TypeError: WebDriver.__init__() got an unexpected keyword argument 'Service'
если совсем без параметров - браузер не запускался, но сейчас прошло
исправлено

2023-08-29 08:29 UTC, itsmealbina commented on pages/base_page.py
> +class Base():
спасибо =)

2023-08-30 10:23 UTC, merged